#!/bin/bash

export GO111MODULE=on 
export GOPROXY=https://goproxy.cn
# build webhook
CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o admission-webhook-security
# build docker image
docker build --no-cache -t daocloud.io/daocloud/admission-webhook-security:latest .
rm -rf admission-webhook-security

docker push daocloud.io/daocloud/admission-webhook-security:latest
