apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-security-cfg
  labels:
    app: admission-webhook-security
webhooks:
  - name: mutating-security.datacreating.com
    clientConfig:
      service:
        name: admission-webhook-security-svc
        namespace: jiexun-test
        path: "/mutate"
      caBundle: ${CA_BUNDLE}
    rules:
      - operations: ["CREATE"]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]
    namespaceSelector:
      matchLabels:
        admission-webhook-security: enabled
    timeoutSeconds: 5
